### ISSUE TITLE
pretrained weights link broken

### ISSUE THREAD

**Issue by alexmehta** [honghai-nguyen/ABAW3-VAEstimation#1]
these 2 links are dead:

    SENet50: https://drive.google.com/file/d/19mdm-KGdDvoVl4tUnhPNbli5cNx0lH1V/view?usp=sharing
    ResNet50: https://drive.google.com/file/d/1YgSWFMG-DtMJUs5KTssJR0-HETpbyPTK/view?usp=sharing

**Comment by honghai-nguyen** [comment]
Our method does not use SENet and ResNet backbone, so we deleted it.

**Comment by honghai-nguyen** [comment]
> these 2 links are dead:
> 
> ```
> SENet50: https://drive.google.com/file/d/19mdm-KGdDvoVl4tUnhPNbli5cNx0lH1V/view?usp=sharing
> ResNet50: https://drive.google.com/file/d/1YgSWFMG-DtMJUs5KTssJR0-HETpbyPTK/view?usp=sharing
> ```

Our method does not use SENet and ResNet backbone, so we deleted it.

**Comment by alexmehta** [comment]
Thanks for the reply. Makes sense. I'll close this issue.
